### ISSUE TITLE
Screen flicker every one second.

### ISSUE THREAD

**Issue by liugangnhm** [gizak/termui#65] opened 2015-11-12 11:26 UTC
When I run dashboard demo ,my screen flicker every one second when screen is rerender.

I use putty to login Ubuntu 14.

It also occurred on my MacBook Pro with Mac OS X 10.10.

I will upload an gif picture to show the issue.

**Comment by byrnedo** [comment] 2015-11-12 15:23
Duplicate of #61

**Closed** 2015-12-09 19:08 UTC
