### ISSUE TITLE
Text editing?

### ISSUE THREAD

**Issue by nickfromXXII** [gizak/termui#156] opened 2017-06-24 13:37 UTC
Hello,
I want to use this package to create a client for messenger, but I haven't found any information about widgets providing text editing. Is there possibility to edit text in the widgets? If not, is this feature already planned?

**Comment by hvze** [comment] 2018-01-29 06:35
I've sort of manipulated this by creating my own text buffer and using a wrapper struct, good luck getting text wrapping to work dynamically.

**Comment by cjbassi** [comment] 2019-01-24 09:16
Definitely something I'd like to add. This seems like a duplicate of #34 tho so I'm going to close this.

**Closed by cjbassi** 2019-01-24 09:16 UTC
Labels: enhancement
