### ISSUE TITLE
Great project, is it still maintained ?

### ISSUE THREAD

**Issue by vladimirvivien** [gizak/termui#164] opened 2017-09-17 17:10 UTC
@gizak  
I see many PR's hanging around with no resolution.  Is this project still active?

**Comment by pdevine** [comment] 2017-11-24 18:38
Wondering the same thing.

**Comment by pdevine** [comment] 2017-12-11 21:39
The biggest issue (aside from none of the pull requests being merged) seems to be lack of focusable widgets IMO.  Maybe we should do a fork?

**Comment by ont** [comment] 2017-12-17 10:48
According to @gizak 's profile, his last activity on github was in 2017 may... Sounds not very good.

**Comment by stephencheng** [comment] 2018-02-19 04:47
Anyone would like to fork and continue with new feature development? The main headache I had is the data racing and I have no idea how to easily fix in my own code.

**Comment by ttacon** [comment] 2018-03-28 00:52
Hey folks, not to be that person - but the recent breaking changes in panicparse (see #177 ) led me to create a fork [here](https://github.com/ttacon/termui). If there's enough interest I'm happy enough to help ensure PRs get added in a quick enough time frame - I also added `dep` in that fork too.

**Comment by pdevine** [comment] 2018-04-14 18:54
I see @gizak merged something in January, which I think was the breaking change, but there hasn't been anything since then.

As I mentioned in my comment last December, not having a concept of having focusable widgets is pretty much a deal breaker for most applications.  What I was trying to do with termui is probably a lot different than what most people are doing though, because I was trying to develop a sprite library so that you can animate ascii objects and move them around the screen.  I always found the way termui handles Buffer objects to be cumbersome.

Anyway, I gave up and just started using `termbox-go` directly, which is what termui is based upon.  My supposition though is instead of a fork, we need something better to be able to handle focusable widgets in a sane way.  And that probably means a rewrite instead of a fork.

**Comment by mum4k** [comment] 2018-06-13 16:35
(fyi) I too found this project very useful. With the conclusion that it is no longer maintained and its current state means larger maintenance burden than I could take on I have started a rewrite. 

https://github.com/mum4k/termdash

Contributions / comments welcome.

**Comment by vladimirvivien** [comment] 2018-06-18 16:29
@mum4k thanks for sharing.  Is this a Google project ? I asked because it requires a Google CLA for contributing.

**Comment by vladimirvivien** [comment] 2018-06-19 14:44
@mum4k thanks for clarifying... Also wanted to point out to all on this thread that developer @cjbassi also has a working fork of termui and used to create gotop - https://github.com/cjbassi/termui

**Comment by cjbassi** [comment] 2018-08-02 22:18
It's still maintained! I was just added as a co-maintainer and I'll be working on getting through the current pr's and then start prioritizing issues to work on. From this thread I can tell focusable widgets and data racing is a a priority, and of course any breaking bugs like the one caused by panicparse (which I think I already fixed). Feel free to create any pr's since I'll be working through those now.

**Closed by cjbassi** 2018-08-02 22:18 UTC
